# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadingWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time


class Load_Window(QtWidgets.QDialog):
    def __init__(self):
        QtWidgets.QDialog.__init__(self)
        self.resize(500, 500)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(150, 40, 201, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setGeometry(QtCore.QRect(150, 220, 200, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(0, 260, 500, 221))
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.ActionLog = []

        self.show()

        self.retranslateUi(self)

    def toPercentage(self, value, total):
        percentage = (value/total)*100
        if percentage > 100:
            print("WARN: Percentage is Greater than 100!")
        return percentage

    def updateActionLog(self, action): # adds "action" to action log
        _translate = QtCore.QCoreApplication.translate
        self.ActionLog.reverse()
        self.ActionLog.append(str(action))
        while len(self.ActionLog) > 16:
            print(f"WARN: LEN {len(self.ActionLog)}")
            self.ActionLog.pop(0)
        self.ActionLog.reverse()
        ActionLog = '\n'.join(self.ActionLog)
        #print(ActionLog)
        #print()
        self.label_2.setText(_translate("Load_Window", f"{ActionLog}"))

    def updateProgressBar(self, index, total): # index, total will calculate percentage inside function
        self.progressBar.setValue(int(round(self.toPercentage(index, total), 0)))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Load_Window", "Loading..."))
        self.label_2.setText(_translate("Load_Window", f"{self.ActionLog}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    #Form = QtWidgets.QWidget()
    LW = Load_Window()
    app.processEvents()

    for i in range(200000):
        LW.updateProgressBar(i, 200000)
        LW.updateActionLog(f"{i}/200000")
        #time.sleep(0.1)

    #time.sleep(5)
    #LW.close()
    #ui.setupUi(Form)
    #Form.show()
    sys.exit(app.exec_())
