# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Command = QtWidgets.QPushButton(self.centralwidget)
        self.Command.setEnabled(False)
        self.Command.setGeometry(QtCore.QRect(350, 10, 93, 28))
        self.Command.setObjectName("Command")
        self.Output = QtWidgets.QLabel(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(170, 140, 451, 321))
        self.Output.setAutoFillBackground(True)
        self.Output.setFrameShape(QtWidgets.QFrame.Box)
        self.Output.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Output.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Output.setObjectName("Output")
        self.Parameters = QtWidgets.QLineEdit(self.centralwidget)
        self.Parameters.setGeometry(QtCore.QRect(340, 50, 113, 22))
        self.Parameters.setObjectName("Parameters")
        self.Process = QtWidgets.QPushButton(self.centralwidget)
        self.Process.setGeometry(QtCore.QRect(350, 100, 93, 28))
        self.Process.setCheckable(False)
        self.Process.setChecked(False)
        self.Process.setDefault(False)
        self.Process.setObjectName("Process")
        self.ProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.ProgressBar.setEnabled(True)
        self.ProgressBar.setGeometry(QtCore.QRect(70, 490, 661, 21))
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.ProgressBar.setTextVisible(True)
        self.ProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressBar.setObjectName("ProgressBar")
        self.progressText = QtWidgets.QLabel(self.centralwidget)
        self.progressText.setGeometry(QtCore.QRect(144, 470, 511, 20))
        self.progressText.setAlignment(QtCore.Qt.AlignCenter)
        self.progressText.setObjectName("progressText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.GroupGenerator = QtWidgets.QMenu(self.menubar)
        self.GroupGenerator.setObjectName("GroupGenerator")
        self.menuStart_Module = QtWidgets.QMenu(self.GroupGenerator)
        self.menuStart_Module.setObjectName("menuStart_Module")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionCheck_for_Update = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Update.setObjectName("actionCheck_for_Update")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionGroup_Generator = QtWidgets.QAction(MainWindow)
        self.actionGroup_Generator.setObjectName("actionGroup_Generator")
        self.menuStart_Module.addAction(self.actionGroup_Generator)
        self.GroupGenerator.addAction(self.actionCheck_for_Update)
        self.GroupGenerator.addSeparator()
        self.GroupGenerator.addAction(self.menuStart_Module.menuAction())
        self.menubar.addAction(self.GroupGenerator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Command.setText(_translate("MainWindow", "{Command}"))
        self.Output.setText(_translate("MainWindow", "{output}"))
        self.Parameters.setPlaceholderText(_translate("MainWindow", "{params}"))
        self.Process.setText(_translate("MainWindow", "Process"))
        self.progressText.setText(_translate("MainWindow", "ProgressText"))
        self.GroupGenerator.setTitle(_translate("MainWindow", "Main"))
        self.menuStart_Module.setTitle(_translate("MainWindow", "Start Module"))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File"))
        self.actionCheck_for_Update.setText(_translate("MainWindow", "Check for Update"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionGroup_Generator.setText(_translate("MainWindow", "Group Generator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
