# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModuleStore.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ModuleList


class Ui_ModuleStore(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(Ui_ModuleStore, self).__init__(parent)

        self.Modules = QtWidgets.QListWidget(self)
        self.Modules.setGeometry(QtCore.QRect(10, 10, 256, 561))
        self.Modules.itemClicked.connect(self.display)
        self.Modules.setObjectName("Modules")
        self.Desc = QtWidgets.QFrame(self)
        self.Desc.setGeometry(QtCore.QRect(269, 9, 491, 501))
        self.Desc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Desc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Desc.setObjectName("Desc")
        self.Details = QtWidgets.QLabel(self.Desc)
        self.Details.setGeometry(QtCore.QRect(0, 395, 491, 101))
        self.Details.setAutoFillBackground(True)
        self.Details.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Details.setObjectName("Details")
        self.ModLabel = QtWidgets.QLabel(self.Desc)
        self.ModLabel.setGeometry(QtCore.QRect(0, 0, 491, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ModLabel.setFont(font)
        self.ModLabel.setAutoFillBackground(True)
        self.ModLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ModLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ModLabel.setObjectName("ModLabel")
        self.DescLabel = QtWidgets.QLabel(self.Desc)
        self.DescLabel.setGeometry(QtCore.QRect(0, 70, 491, 311))
        self.DescLabel.setAutoFillBackground(True)
        self.DescLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.DescLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.DescLabel.setObjectName("DescLabel")
        self.Un_Install = QtWidgets.QPushButton(self)
        self.Un_Install.setGeometry(QtCore.QRect(660, 540, 93, 28))
        self.Un_Install.setObjectName("Un_Install")
        self.Update = QtWidgets.QPushButton(self)
        self.Update.setGeometry(QtCore.QRect(560, 540, 93, 28))
        self.Update.setObjectName("Update")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(270, 540, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.installBar = QtWidgets.QProgressBar(self)
        self.installBar.setGeometry(QtCore.QRect(370, 540, 181, 23))
        self.installBar.setProperty("value", 24)
        self.installBar.setObjectName("installBar")
        self.installStatus = QtWidgets.QLabel(self)
        self.installStatus.setGeometry(QtCore.QRect(370, 520, 55, 16))
        self.installStatus.setObjectName("installStatus")

        self.retranslateUi()

        self.fillList()

    def display(self, item):
        print(repr(item))

    def fillList(self):
        _, modDict = ModuleList.loadModules()

        for item in modDict:
            print(modDict[item])
            modDict[item]["QItem"] = QtWidgets.QListWidgetItem(modList[item]["Name"])
            self.Modules.addItem(modDict[item]["QItem"])

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Details.setText(_translate("ModuleStore", "{Author/Requestor Details}"))
        self.ModLabel.setText(_translate("ModuleStore", "{ModuleName}"))
        self.DescLabel.setText(_translate("ModuleStore", "{Description}"))
        self.Un_Install.setText(_translate("ModuleStore", "{Install/Uninstall}"))
        self.Update.setText(_translate("ModuleStore", "{Update}"))
        self.pushButton.setText(_translate("ModuleStore", "Report"))
        self.installStatus.setText(_translate("ModuleStore", "{Status}"))

class MainUI:
    def setupUi(self, ModuleStore):
        
        ModuleStore.setObjectName("ModuleStore")
        ModuleStore.resize(772, 579)

        self.centralwidget = QtWidgets.QStackedWidget()

        ModuleStore.setCentralWidget(self.centralwidget)

        self.MS = Ui_ModuleStore()
        self.centralwidget.addWidget(self.MS)
        self.centralwidget.setCurrentWidget(self.MS)

        self.retranslateUi(ModuleStore)
        QtCore.QMetaObject.connectSlotsByName(ModuleStore)

    def retranslateUi(self, ModuleStore):
        _translate = QtCore.QCoreApplication.translate
        ModuleStore.setWindowTitle(_translate("ModuleStore", "Module Store"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModuleStore = QtWidgets.QMainWindow()
    ui = MainUI()
    ui.setupUi(ModuleStore)
    ModuleStore.show()
    sys.exit(app.exec_())
