# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Update(object):
    def setupUi(self, Update):
        Update.setObjectName("Update")
        Update.resize(800, 600)
        self.progressBar = QtWidgets.QProgressBar(Update)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(10, 60, 781, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(Update)
        self.label.setGeometry(QtCore.QRect(10, 15, 781, 41))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Update)
        self.pushButton.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Update)
        self.label_2.setGeometry(QtCore.QRect(6, 82, 791, 471))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Update)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 560, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Update)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 560, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Update)
        QtCore.QMetaObject.connectSlotsByName(Update)

    def retranslateUi(self, Update):
        _translate = QtCore.QCoreApplication.translate
        Update.setWindowTitle(_translate("Update", "Form"))
        self.label.setText(_translate("Update", "{Current Activity}"))
        self.pushButton.setText(_translate("Update", "Show More Info"))
        self.label_2.setText(_translate("Update", "{Activity Log} [TOP->BOTTOM]"))
        self.pushButton_2.setText(_translate("Update", "Cancel"))
        self.pushButton_3.setText(_translate("Update", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Update = QtWidgets.QWidget()
    ui = Ui_Update()
    ui.setupUi(Update)
    Update.show()
    sys.exit(app.exec_())
