# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModStore.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ModStoreWidget(QtWidgets.QWidget):
    def setupUi(self, parent=None):
        super(ModStoreWidget, self).__init__(parent)
        self.ModuleList = QtWidgets.QListWidget(self)
        self.ModuleList.setGeometry(QtCore.QRect(10, 10, 271, 581))
        self.ModuleList.setObjectName("ModuleList")
        self.Details = QtWidgets.QWidget(self)
        self.Details.setGeometry(QtCore.QRect(290, 10, 501, 581))
        self.Details.setObjectName("Details")
        self.progressBar = QtWidgets.QProgressBar(self.Details)
        self.progressBar.setGeometry(QtCore.QRect(100, 550, 301, 28))
        self.progressBar.setMaximum(1000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.Report = QtWidgets.QPushButton(self.Details)
        self.Report.setGeometry(QtCore.QRect(0, 520, 93, 28))
        self.Report.setObjectName("Report")
        self.Name = QtWidgets.QLabel(self.Details)
        self.Name.setGeometry(QtCore.QRect(4, 5, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Name.setFont(font)
        self.Name.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Name.setLineWidth(1)
        self.Name.setMidLineWidth(0)
        self.Name.setScaledContents(False)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.Action = QtWidgets.QPushButton(self.Details)
        self.Action.setGeometry(QtCore.QRect(410, 550, 93, 28))
        self.Action.setObjectName("Action")
        self.MDetails = QtWidgets.QLabel(self.Details)
        self.MDetails.setGeometry(QtCore.QRect(4, 74, 491, 321))
        self.MDetails.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.MDetails.setObjectName("MDetails")
        self.Author = QtWidgets.QLabel(self.Details)
        self.Author.setGeometry(QtCore.QRect(4, 393, 491, 121))
        self.Author.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Author.setObjectName("Author")
        self.Feedback = QtWidgets.QPushButton(self.Details)
        self.Feedback.setGeometry(QtCore.QRect(0, 550, 93, 28))
        self.Feedback.setObjectName("Feedback")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Report.setText(_translate("Form", "Report"))
        self.Name.setText(_translate("Form", "{ModuleName}"))
        self.Action.setText(_translate("Form", "{Action}"))
        self.MDetails.setText(_translate("Form", "TextLabel"))
        self.Author.setText(_translate("Form", "TextLabel"))
        self.Feedback.setText(_translate("Form", "Feedback"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
